-- ============================================================================
-- E-PKL Multi-Tenant Database Schema
-- ============================================================================
-- This migration sets up the multi-tenant foundation for E-PKL SaaS
-- It adds tenant isolation to existing E-PKL tables
-- ============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. TENANTS TABLE (New)
-- ============================================================================
CREATE TABLE public.tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  subdomain TEXT UNIQUE NOT NULL,
  plan TEXT DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'enterprise')),
  max_students INTEGER DEFAULT 50,
  max_teachers INTEGER DEFAULT 5,
  max_companies INTEGER DEFAULT 10,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on tenants table
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 2. TENANT_MEMBERS TABLE (New - Links users to tenants with roles)
-- ============================================================================
CREATE TABLE public.tenant_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  user_id UUID NOT NULL, -- References auth.users or external auth provider
  role TEXT NOT NULL CHECK (role IN ('super_admin', 'admin', 'teacher', 'student')),
  is_primary BOOLEAN DEFAULT false, -- Is this the user's primary tenant
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(tenant_id, user_id)
);

-- Enable RLS on tenant_members table
ALTER TABLE public.tenant_members ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 3. PROFILES TABLE (Modified - Added tenant_id)
-- ============================================================================
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY, -- References auth.users or external auth
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  nisn TEXT, -- Student ID (unique within tenant)
  full_name TEXT,
  class_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(tenant_id, nisn)
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 4. COMPANIES TABLE (Modified - Added tenant_id)
-- ============================================================================
CREATE TABLE public.companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  radius_meter INTEGER DEFAULT 100,
  address TEXT,
  phone TEXT,
  contact_person TEXT,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on companies
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5. PLACEMENTS TABLE (Modified - Added tenant_id)
-- ============================================================================
CREATE TABLE public.placements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  mentor_name TEXT, -- Company mentor name
  mentor_phone TEXT,
  start_date DATE,
  end_date DATE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on placements
ALTER TABLE public.placements ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 6. ATTENDANCE_LOGS TABLE (Modified - Added tenant_id)
-- ============================================================================
CREATE TABLE public.attendance_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  placement_id BIGINT REFERENCES public.placements(id) ON DELETE SET NULL,
  check_in_time TIMESTAMPTZ DEFAULT NOW(),
  check_out_time TIMESTAMPTZ,
  check_in_lat DOUBLE PRECISION,
  check_in_long DOUBLE PRECISION,
  check_out_lat DOUBLE PRECISION,
  check_out_long DOUBLE PRECISION,
  photo_url TEXT,
  status TEXT CHECK (status IN ('Hadir', 'Telat', 'Izin', 'Alpha')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on attendance_logs
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 7. DAILY_JOURNALS TABLE (Modified - Added tenant_id)
-- ============================================================================
CREATE TABLE public.daily_journals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  placement_id BIGINT REFERENCES public.placements(id) ON DELETE SET NULL,
  activity_title TEXT,
  description TEXT,
  evidence_photo TEXT,
  date DATE DEFAULT CURRENT_DATE,
  is_approved BOOLEAN DEFAULT false,
  approved_by UUID REFERENCES public.profiles(id),
  approved_at TIMESTAMPTZ,
  feedback TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on daily_journals
ALTER TABLE public.daily_journals ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 8. RLS POLICIES FOR TENANT ISOLATION
-- ============================================================================

-- Helper function to get current user's tenant_id
CREATE OR REPLACE FUNCTION public.get_current_tenant_id()
RETURNS UUID AS $$
DECLARE
  tenant_id UUID;
BEGIN
  SELECT tm.tenant_id INTO tenant_id
  FROM public.tenant_members tm
  WHERE tm.user_id = auth.uid()
  LIMIT 1;
  RETURN tenant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper function to check if user is admin of tenant
CREATE OR REPLACE FUNCTION public.is_tenant_admin(tenant_uuid UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.tenant_members tm
    WHERE tm.tenant_id = tenant_uuid
    AND tm.user_id = auth.uid()
    AND tm.role IN ('admin', 'super_admin')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper function to check if user is teacher of tenant
CREATE OR REPLACE FUNCTION public.is_tenant_teacher(tenant_uuid UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.tenant_members tm
    WHERE tm.tenant_id = tenant_uuid
    AND tm.user_id = auth.uid()
    AND tm.role IN ('teacher', 'admin', 'super_admin')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- TENANTS RLS POLICIES
-- ============================================================================

-- Super admins can manage all tenants
CREATE POLICY "Super admins can manage all tenants" ON public.tenants
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Users can view their own tenants
CREATE POLICY "Users can view their own tenants" ON public.tenants
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.tenant_id = tenants.id
      AND tm.user_id = auth.uid()
    )
  );

-- ============================================================================
-- TENANT_MEMBERS RLS POLICIES
-- ============================================================================

-- Super admins can manage all tenant members
CREATE POLICY "Super admins can manage all tenant members" ON public.tenant_members
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Admins can manage members in their tenant
CREATE POLICY "Admins can manage members in their tenant" ON public.tenant_members
  FOR ALL USING (
    tenant_id IN (
      SELECT tm.tenant_id FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role IN ('admin', 'super_admin')
    )
  );

-- Users can view members in their tenant
CREATE POLICY "Users can view members in their tenant" ON public.tenant_members
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.tenant_id = tenant_members.tenant_id
      AND tm.user_id = auth.uid()
    )
  );

-- ============================================================================
-- PROFILES RLS POLICIES
-- ============================================================================

-- Super admins can manage all profiles
CREATE POLICY "Super admins can manage all profiles" ON public.profiles
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Admins and teachers can manage profiles in their tenant
CREATE POLICY "Admins and teachers can manage profiles in their tenant" ON public.profiles
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.tenant_id = profiles.tenant_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('admin', 'teacher', 'super_admin')
    )
  );

-- Students can view own profile
CREATE POLICY "Students can view own profile" ON public.profiles
  FOR SELECT USING (
    id = auth.uid()
  );

-- Students can update own profile (limited fields)
CREATE POLICY "Students can update own profile" ON public.profiles
  FOR UPDATE USING (
    id = auth.uid()
  );

-- ============================================================================
-- COMPANIES RLS POLICIES
-- ============================================================================

-- Super admins can manage all companies
CREATE POLICY "Super admins can manage all companies" ON public.companies
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Admins and teachers can manage companies in their tenant
CREATE POLICY "Admins and teachers can manage companies in their tenant" ON public.companies
  FOR ALL USING (
    is_tenant_admin(companies.tenant_id) OR is_tenant_teacher(companies.tenant_id)
  );

-- All users can view companies in their tenant
CREATE POLICY "Users can view companies in their tenant" ON public.companies
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.tenant_id = companies.tenant_id
      AND tm.user_id = auth.uid()
    )
  );

-- ============================================================================
-- PLACEMENTS RLS POLICIES
-- ============================================================================

-- Super admins can manage all placements
CREATE POLICY "Super admins can manage all placements" ON public.placements
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Admins and teachers can manage placements in their tenant
CREATE POLICY "Admins and teachers can manage placements in their tenant" ON public.placements
  FOR ALL USING (
    is_tenant_admin(placements.tenant_id) OR is_tenant_teacher(placements.tenant_id)
  );

-- Students can view their own placements
CREATE POLICY "Students can view own placements" ON public.placements
  FOR SELECT USING (
    student_id = auth.uid()
  );

-- ============================================================================
-- ATTENDANCE_LOGS RLS POLICIES
-- ============================================================================

-- Super admins can manage all attendance logs
CREATE POLICY "Super admins can manage all attendance logs" ON public.attendance_logs
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Admins and teachers can manage attendance in their tenant
CREATE POLICY "Admins and teachers can manage attendance in their tenant" ON public.attendance_logs
  FOR ALL USING (
    is_tenant_admin(attendance_logs.tenant_id) OR is_tenant_teacher(attendance_logs.tenant_id)
  );

-- Students can insert own attendance
CREATE POLICY "Students can insert own attendance" ON public.attendance_logs
  FOR INSERT WITH CHECK (
    student_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.tenant_id = attendance_logs.tenant_id
      AND tm.user_id = auth.uid()
    )
  );

-- Students can view own attendance
CREATE POLICY "Students can view own attendance" ON public.attendance_logs
  FOR SELECT USING (
    student_id = auth.uid() OR
    is_tenant_teacher(attendance_logs.tenant_id)
  );

-- ============================================================================
-- DAILY_JOURNALS RLS POLICIES
-- ============================================================================

-- Super admins can manage all journals
CREATE POLICY "Super admins can manage all journals" ON public.daily_journals
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.user_id = auth.uid()
      AND tm.role = 'super_admin'
    )
  );

-- Admins and teachers can manage journals in their tenant
CREATE POLICY "Admins and teachers can manage journals in their tenant" ON public.daily_journals
  FOR ALL USING (
    is_tenant_admin(daily_journals.tenant_id) OR is_tenant_teacher(daily_journals.tenant_id)
  );

-- Students can insert own journals
CREATE POLICY "Students can insert own journals" ON public.daily_journals
  FOR INSERT WITH CHECK (
    student_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM public.tenant_members tm
      WHERE tm.tenant_id = daily_journals.tenant_id
      AND tm.user_id = auth.uid()
    )
  );

-- Students can update own unapproved journals
CREATE POLICY "Students can update own unapproved journals" ON public.daily_journals
  FOR UPDATE USING (
    student_id = auth.uid() AND is_approved = false
  );

-- Students can view own journals
CREATE POLICY "Students can view own journals" ON public.daily_journals
  FOR SELECT USING (
    student_id = auth.uid()
  );

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Tenant indexes
CREATE INDEX idx_tenants_subdomain ON public.tenants(subdomain);
CREATE INDEX idx_tenants_status ON public.tenants(status);

-- Tenant members indexes
CREATE INDEX idx_tenant_members_tenant_id ON public.tenant_members(tenant_id);
CREATE INDEX idx_tenant_members_user_id ON public.tenant_members(user_id);
CREATE INDEX idx_tenant_members_role ON public.tenant_members(role);

-- Profiles indexes
CREATE INDEX idx_profiles_tenant_id ON public.profiles(tenant_id);
CREATE INDEX idx_profiles_nisn ON public.profiles(tenant_id, nisn);

-- Companies indexes
CREATE INDEX idx_companies_tenant_id ON public.companies(tenant_id);

-- Placements indexes
CREATE INDEX idx_placements_tenant_id ON public.placements(tenant_id);
CREATE INDEX idx_placements_student_id ON public.placements(student_id);
CREATE INDEX idx_placements_company_id ON public.placements(company_id);

-- Attendance indexes
CREATE INDEX idx_attendance_logs_tenant_id ON public.attendance_logs(tenant_id);
CREATE INDEX idx_attendance_logs_student_id ON public.attendance_logs(student_id);
CREATE INDEX idx_attendance_logs_date ON public.attendance_logs(check_in_time);

-- Journals indexes
CREATE INDEX idx_daily_journals_tenant_id ON public.daily_journals(tenant_id);
CREATE INDEX idx_daily_journals_student_id ON public.daily_journals(student_id);
CREATE INDEX idx_daily_journals_date ON public.daily_journals(date);

-- ============================================================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add updated_at triggers to all tables
CREATE TRIGGER update_tenants_updated_at BEFORE UPDATE ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_tenant_members_updated_at BEFORE UPDATE ON public.tenant_members
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON public.companies
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_placements_updated_at BEFORE UPDATE ON public.placements
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_attendance_logs_updated_at BEFORE UPDATE ON public.attendance_logs
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_daily_journals_updated_at BEFORE UPDATE ON public.daily_journals
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
